dist: trusty
language: java
jdk:
  - oraclejdk8
script:
  - chmod -R ug+x .travis
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then bash ./travis/run_on_pull_request; else then bash ./travis/run_on_merge_request; fi

after_success:
      - bash <(curl -s https://codecov.io/bash)